[metadata]
name = HyProxy
version = 0.1.0
description = An asynchronous HTTP, SOCKS4, and SOCKS5 proxy server.
long_description = file: README.md
long_description_content_type = text/markdown
author = haytam.cho
author_email = charcaouhaitam1@gmail.com
keywords = asyncio, http, proxy, socks4, socks5
classifiers =
    Development Status :: 3 - Alpha
    Intended Audience :: Developers
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Programming Language :: Python :: 3.13
    Topic :: Internet :: Proxy Servers
project_urls =
    Homepage = https://github.com/Arcade-m7/HyProxy
    Repository = https://github.com/Arcade-m7/HyProxy

[options]
include_package_data = True
zip_safe = False

[flake8]
max-line-length = 100
extend-ignore = E203
exclude =
    .git,
    .pytest_cache,
    __pycache__,
    build,
    dist
